### PR TITLE
Proper naming for things, some annotation

### PR DESCRIPTION
**Pull request by sgb-io**
Make the project far more readable.

Annotations courtesy of @zz85 - via https://gist.github.com/zz85/25564f1910f1877c39c25ace5e5159bc

### CODE REVIEW

**Comment by developit** [comment]
Hi @sgb-io - it looks like we did this at the same time! I'll check to see if there are any additional annotations in yours I missed.

**Comment by sgb-io** [comment]
Ah, indeed! Let me know if there's anything in here you like and I can rebase it, otherwise feel free to close!

**Comment by developit** [comment]
I merged your definitions as part of a complete refactoring. I'll add you for credit in the source code :)

**Comment by developit** [comment]
You're in the [readme now](https://github.com/developit/greenlet#license--credits) :)

**Comment by sgb-io** [comment]
Thanks!

**Pull request closed without merging**
